Step through `total_steps` instead of epochs.
PROBIC/opacus pull request #3
Opened 2023-11-06 13:01 UTC by ikanher

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Motivation and Context / Related issue

Currently only sample rates of 1/num_batches are supported due to the way the data loaders are handled.

To have total control over sample rate, added a parameter `total_steps` to make_private and make_private_with_epsilon. When the parameter is set we will step `total_steps` of times through the data loader instead of approximated epochs. The sample rate is also exactly set to q = B/N.

## How Has This Been Tested (if it applies)

Added a new test `test_make_private_with_epsilon_with_total_steps` to tests/privacy_engine_test.py.

It tests a few different `total_steps`, `data_size`, and `batch_size` combinations and checks that the accounting history in fact contains the correct sample rates. In addition it also check the `target_epsilon` according to the existing `test_make_private_with_epsilon` test.
 
## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [ ] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [] All tests passed, and additional code has been covered with new tests.

We have been failing to run the Opacus test suite without errors.

However, the change did not introduce any _new_ failing tests.

2023-11-07 07:45 UTC, Solosneros requested changes
I would like to get rid of this one epochs=1 in the test if possible. I think it is just left over?

2023-11-07 07:45 UTC, Solosneros commented on opacus/tests/privacy_engine_test.py
> +        epochs = 1
What is this epochs=1 doing here?

2023-11-07 07:45 UTC, Solosneros commented on opacus/tests/privacy_engine_test.py
> +    def test_make_private_with_epsilon_with_total_steps(self, total_steps, batch_size, data_size):
good test!

2023-11-07 07:45 UTC, Solosneros commented on opacus/tests/privacy_engine_test.py
> +    def test_make_private_with_epsilon_with_total_steps(self, total_steps, batch_size, data_size):
are they testing the accounting history with the usual `make_private_with_epsilon`?

2023-11-07 07:52 UTC, ikanher commented on opacus/tests/privacy_engine_test.py
> +        epochs = 1
Well, epochs have to be set to 1 if total_steps are set for the accounting to work, because we are using sample rate q = B/N?

In fact, I realized yesterday someone could accidentally set epochs to something else and added this to `make_private_with_epsilon`:

```
            if epochs != 1:
                raise ValueError("Epochs must be 1 when 'total_steps' is set")
```

What's your take on this? Force set epochs to 1 when `total_steps` is set?

2023-11-07 07:54 UTC, ikanher commented on opacus/tests/privacy_engine_test.py
> +    def test_make_private_with_epsilon_with_total_steps(self, total_steps, batch_size, data_size):
No, they are not. Opacus devs just check the target epsilon.

2023-11-07 09:14 UTC, ikanher commented on opacus/tests/privacy_engine_test.py
> +        epochs = 1
Based on our discussion changed code to expect that epochs is set to None when `total_steps` is set, which seems like a much better solution. Thanks!

2023-11-09 08:06 UTC, Solosneros commented on opacus/tests/privacy_engine_test.py
> +        epochs = 1
great!

2023-11-09 08:07 UTC, Solosneros approved these changes
Looks good now!

2024-01-30 13:55 UTC, merged